export type MinorRequirementGroup = {
  id: string;
  title: string;
  requiredCount: number;
  courseCodes: string[];
  countsTowardMinor: boolean;
  note?: string;
};

export type MinorDefinition = {
  code: string;
  name: string;
  totalCreditsRequired?: number;
  groups: MinorRequirementGroup[];
};

export const MINORS: MinorDefinition[] = [
  {
    code: "MGMT",
    name: "Minor in Management",
    totalCreditsRequired: 12,
    groups: [
      {
        id: "prereq-ic252",
        title: "Prerequisite: IC-252",
        requiredCount: 1,
        courseCodes: ["IC-252"],
        countsTowardMinor: false,
      },
      {
        id: "prereq-comm",
        title: "Prerequisite: Communicative Competence",
        requiredCount: 1,
        courseCodes: [
          "HS-105",
          "HS-109",
          "HS-305",
          "HS-357",
          "MB-304",
          "MB-205",
          "MB-305",
        ],
        countsTowardMinor: false,
        note: "Any 1 from the Communicative Competence basket.",
      },
      {
        id: "core-econ",
        title: "Core: Economics (pick 1)",
        requiredCount: 1,
        courseCodes: ["HS-202", "HS-481"],
        countsTowardMinor: true,
      },
      {
        id: "core-mgmt",
        title: "Core: Management (pick 1)",
        requiredCount: 1,
        courseCodes: ["HS-304", "MB-201"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 2,
        courseCodes: [
          "HS-307",
          "MB-203",
          "HS-510",
          "HS-504",
          "MB-307",
          "MB-524",
          "MB-582",
          "MB-526",
          "MB-527",
          "MB-528",
          "MB-562",
          "MB-570",
        ],
        countsTowardMinor: true,
        note: "Any 2 courses (6 credits) from the electives basket.",
      },
    ],
  },
  {
    code: "CSE",
    name: "Minor in Computer Science Engineering",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "prereq-ic253",
        title: "Prerequisite: IC-253 (doesn’t count)",
        requiredCount: 1,
        courseCodes: ["IC-253"],
        countsTowardMinor: false,
        note: "IC-253 is a prerequisite for CS-212, but does not count towards this minor.",
      },
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 1,
        courseCodes: ["CS-212"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 2,
        courseCodes: [
          "CS-313",
          "CS-302",
          "CS-305",
          "CS-214",
          "CS-304",
          "CS-309",
          "CS-208",
          "CS-312",
        ],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "IS",
    name: "Minor in Intelligent Systems",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 3,
        courseCodes: [
          "EE-511",
          "CS-673",
          "CS-671",
          "CS-672",
          "DS-413",
          "DS-411",
          "CS-683",
          "CS-685",
          "CS-305",
          "DS-412",
          "EE-608",
          "BY-606",
          "CS-630",
          "CS-660",
          "CS-609",
        ],
        countsTowardMinor: true,
        note: "No compulsory courses; any counted course should be non P/F and non Audit.",
      },
    ],
  },
  {
    code: "POWER",
    name: "Minor in Power Engineering",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 2,
        courseCodes: ["EE-201", "EE-309"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 1,
        courseCodes: ["CS-403", "CS-304", "CS-214", "CS-309", "CS-671"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "THERMO",
    name: "Minor in Thermo-Fluid Systems",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 3,
        courseCodes: [
          "ME-210",
          "ME-303",
          "ME-307",
          "ME-356",
          "ME-451",
          "ME-614",
          "ME-615",
        ],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "ELECTRONICS",
    name: "Minor in Electronics Engineering",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 2,
        courseCodes: ["EE-203", "EE-210"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 1,
        courseCodes: ["EE-305", "EE-311", "EE-211", "EE-312P"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "COMM",
    name: "Minor in Communication Engineering",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 1,
        courseCodes: ["EE-304"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 2,
        courseCodes: ["EE-503", "EE-314", "EE-530"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "MECH_DES",
    name: "Minor in Mechanical Design",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 3,
        courseCodes: ["ME-205", "ME-309", "ME-206", "ME-352", "ME-305", "ME-602"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "MEAS_INSTR",
    name: "Minor in Measurement and Instrumentation",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 1,
        courseCodes: ["EE-313"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 2,
        courseCodes: ["EE-301", "EE-314", "EE-62010", "EE-62024"],
        countsTowardMinor: true,
        note: "Advanced DSP appears as EE 620 10 / EE 620 24 in the curriculum.",
      },
    ],
  },
  {
    code: "MATERIALS",
    name: "Minor in Device / Structural Materials",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 3,
        courseCodes: ["ME-353", "ME-609", "ME-607", "ME-619"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "CONTROL",
    name: "Minor in Control Engineering",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "compulsory",
        title: "Compulsory",
        requiredCount: 2,
        courseCodes: ["EE-301", "EE-301P"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 1,
        courseCodes: ["EE-509", "EE-514"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "GERMAN",
    name: "Minor in German Language",
    totalCreditsRequired: 9,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 3,
        courseCodes: ["HS-352", "HS-362", "HS-363", "HS-372", "HS-373", "HS-539"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "APPLIED_PHYS",
    name: "Minor in Applied Physics",
    totalCreditsRequired: 12,
    groups: [
      {
        id: "basket",
        title: "Course Basket",
        requiredCount: 4,
        courseCodes: [
          "EP-502",
          "PH-302",
          "PH-522",
          "PH-301",
          "PH-513",
          "PH-501",
          "PH-523",
          "PH-502",
          "PH-503",
          "PH-504",
          "PH-505",
          "PH-506",
          "PH-507",
          "PH-508",
          "PH-511",
          "PH-528",
          "PH-601",
          "PH-603",
          "PH-604",
          "PH-605",
          "PH-606",
          "PH-607",
          "PH-608",
          "PH-609",
          "PH-612",
          "PH-701",
          "PH-706",
        ],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "QUANTUM",
    name: "Minor in Quantum Technologies",
    totalCreditsRequired: 12,
    groups: [
      {
        id: "foundation",
        title: "Foundation (pick 1)",
        requiredCount: 1,
        courseCodes: ["QT-301", "QT-302", "PH-513", "EP-301"],
        countsTowardMinor: true,
        note: "At least one of QT-301 & QT-302/PH-513/EP-301 is mandatory.",
      },
      {
        id: "lab",
        title: "Lab (pick 1)",
        requiredCount: 1,
        courseCodes: ["QT-303P", "QT-304P", "QT-501P"],
        countsTowardMinor: true,
        note: "At least one of QT-303P & QT-304P/QT-501P is mandatory.",
      },
      {
        id: "advanced",
        title: "Advanced (pick 1)",
        requiredCount: 1,
        courseCodes: ["QT-405", "CS-520", "QT-406", "QT-407", "QT-408", "PH-532", "PH-501"],
        countsTowardMinor: true,
        note: "At least one of QT-405/CS-520, QT-406, QT-407, QT-408/PH-532/PH-501 is mandatory.",
      },
      {
        id: "optional",
        title: "Additional (pick 1)",
        requiredCount: 1,
        courseCodes: ["QT-509", "QT-510", "PH-601", "QT-511", "PH-550", "CS-521"],
        countsTowardMinor: true,
      },
    ],
  },
  {
    code: "ROBOTICS",
    name: "Minor in Robotics",
    totalCreditsRequired: 12,
    groups: [
      {
        id: "compulsory-1",
        title: "Compulsory: Robot Kinematics/Dynamics/Control (pick 1)",
        requiredCount: 1,
        courseCodes: ["AR-501", "ME-452"],
        countsTowardMinor: true,
      },
      {
        id: "compulsory-2",
        title: "Compulsory: Mechatronics",
        requiredCount: 1,
        courseCodes: ["AR-503"],
        countsTowardMinor: true,
      },
      {
        id: "electives",
        title: "Electives",
        requiredCount: 2,
        courseCodes: [
          "AR-502",
          "AR-504",
          "AR-505",
          "AR-506",
          "AR-507",
          "AR-508",
          "AR-509",
          "AR-510",
          "AR-511",
          "AR-512",
          "AR-513",
          "AR-514",
          "AR-515",
          "AR-519",
          "EE-555",
        ],
        countsTowardMinor: true,
        note: "Any 2 out of the electives list (as per curriculum).",
      },
    ],
  },
];
